### ISSUE TITLE
BUILD ERROR

### ISSUE THREAD

**Issue by qwfys** [jetty-project/jasper-jsp#1]
<plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>9.2.7.v20150116</version>
                <configuration>
                    <stopKey>stop</stopKey>
                    <stopPort>5599</stopPort>
                    <webAppConfig>
                        <contextPath>/</contextPath>
                    </webAppConfig>
                    <scanIntervalSeconds>0</scanIntervalSeconds>
                    <connectors>
                        <connector implementation="org.eclipse.jetty.server.nio.SelectChannelConnector">
                            <port>80</port>
                            <maxIdleTime>60000</maxIdleTime>
                        </connector>
                    </connectors>
                </configuration>
            </plugin>

[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: org.mortbay.jasper:jasper-jsp:pom:8.0.9.M3

Reason: Cannot find parent: org.eclipse.jetty:jetty-parent for project: org.mortbay.jasper:jasper-jsp:pom:8.0.9.M3 for project org.mortbay.jasper:jasper-jsp:pom:8.0.9.M3

**Comment by janbartel** [comment]
WenkeL,

The paste has not worked properly and most of the output of the build is missing. Can you repaste it please?

Jan

**Comment by joakime** [comment]
If you click on the pencil icon you can see the original paste.

Here it is, but using markdown to make it more visible.

			<plugin>
				<groupId>org.eclipse.jetty</groupId>
				<artifactId>jetty-maven-plugin</artifactId>
				<version>9.2.7.v20150116</version>
				<configuration>
					<stopKey>stop</stopKey>
					<stopPort>5599</stopPort>
					<webAppConfig>
						<contextPath>/</contextPath>
					</webAppConfig>
					<scanIntervalSeconds>0</scanIntervalSeconds>
					<connectors>
						<connector implementation="org.eclipse.jetty.server.nio.SelectChannelConnector">
							<port>80</port>
							<maxIdleTime>60000</maxIdleTime>
						</connector>
					</connectors>
				</configuration>
			</plugin>

**Comment by janbartel** [comment]
Mmn, sorry but from the pasted content on the bug report I can't understand what the jetty maven plugin has got to do with a build of the jetty-jasper project. I've checkout tag 8.0.9.M3 and cleared my local repo of org.eclipse.jetty.jetty-parent, and it builds just fine.  The jetty-parent module version 22 which 8.0.9.M3 depends on is in the maven central repository.  

So whatever project is being built, my suggestion is that WenkeL's local maven repo is borked. Try cleaning and rebuilding.

Jan

**Comment by Danmark** [comment]
i think this is related to http://stackoverflow.com/questions/1885137/maven-downloads-corrupted-jars
and should be solved by https://github.com/jetty-project/jasper-jsp/pull/2

**Comment by janbartel** [comment]
Thanks @Danmark. Closing this issue.
