### ISSUE TITLE
org.mortbay.jasper.* modules contains jakarta packages

### ISSUE THREAD

**Issue by PavelTurk** [jetty-project/jasper-jsp#143]
Both `org.mortbay.jasper.apache-el-10.1.1.jar` and `org.mortbay.jasper.apache-jsp-10.1.1.jar` contain jakarta packages.

`org.mortbay.jasper.apache-el-10.1.1.jar` has `jakarta.el` which must be in `jakarta.el.jakarta.el-api-5.0.0.jar`.

`org.mortbay.jasper.apache-jsp-10.1.1.jar` has `jakarta.servlet.jsp` which must be in `jakarta.servlet.jsp.jakarta.servlet.jsp-api-3.1.0.jar`

This problem doesn't allow to use these modules with JPMS for Jetty 12

**Comment by janbartel** [comment]
The `org.mortbay.jasper` jars have always also contained the `javax.el` (or now its the `jakarta.el`) classes. I was under the impression that jpms was working fine with jsp in jetty-10, jetty-11. Have you tried it in those earlier versions of jetty?

**Comment by janbartel** [comment]
@PavelTurkish can you provide some more information on this? Log output, stacktraces etc? The configuration of the jpms module names hasn't changed since `jetty-10` so I'm having difficulty seeing where the problem is?

**Comment by janbartel** [comment]
@PavelTurkish the jetty-12.0.x distribution tests for jsp with jpms enabled all work, see https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/tests/test-distribution/test-distribution-common/src/test/java/org/eclipse/jetty/tests/distribution/DistributionTests.java#L156. You will need to provide more details or modify the test so it reproduces your issue. And yes, we've all read the spec.

**Comment by janbartel** [comment]
That's more helpful. Thank you, looking into it.

**Comment by janbartel** [comment]
@PavelTurkish  fixed. See jetty project https://github.com/eclipse/jetty.project/pull/9321 and https://github.com/eclipse/jetty.project/pull/9303.
