### ISSUE TITLE
Some JSP pages cannot compile when running in OSGI

### ISSUE THREAD

**Issue by janbartel** [jetty-project/jasper-jsp#93]
This issue rasied over at the jetty project belongs here:  https://github.com/eclipse/jetty.project/issues/4834

**Comment by janbartel** [comment]
Fixed via commits:
https://github.com/jetty-project/jasper-jsp/commit/fe7de0ca0715b270d0af2f8a1a857dd32c3d43cc
https://github.com/jetty-project/jasper-jsp/commit/e329273366c7af2bc63d836dab8964bca5930b5e
https://github.com/jetty-project/jasper-jsp/commit/e9c0ddfd96fd46041b22b03b583ed2770eaa2a80

**Comment by olamy** [comment]
wouldn't it be better to test this via a PR rather than direct commit to `master`? :P
